service:
  name: hidoki-coach

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline

provider:
  name: aws

  runtime: nodejs8.10

functions:
  checker:
    handler: handler.checker
    events:
      - http:
          method: get
          path: checker
